spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
